name: scientific_computing_project

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - ipykernel=5.1.3
  - python=3.8
  - pip
  - anaconda-client
  - bokeh>=1.3
  - ansi2html
  - click
  - conda-build
  - conda-verify
  - fuzzywuzzy
  - joblib
  - cloudpickle
  - jupyterlab
  - nbsphinx
  - numpy
  - pandas
  - pdbpp
  - petsc4py>=3.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy>=1.2.1
  - seaborn
  - sphinx=2.4.4
  - pydata-sphinx-theme>=0.3.0
  - sphinxcontrib-bibtex
  - sqlalchemy>=1.3
  - tox-conda
  - statsmodels
  - dill

  - pip:
    - black
    - blackcellmagic
    - bump2version
    - pre-commit
    - click==7.0
    - pre-commit
    - Py-BOBYQA
    - DFO-LS
    - git+https://github.com/OpenSourceEconomics/estimagic.git@new_tests_optimization
